In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.tensor(np_array)

In [4]:
x_ones = torch.ones_like(x_np)
x_ones

tensor([[1, 1],
        [1, 1]])

In [5]:
x_rand = torch.rand_like(x, dtype=torch.float)

In [6]:
x_rand

tensor([[0.9136, 0.7683],
        [0.2897, 0.4596]])

In [7]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
ones_tensor, zeros_tensor, rand_tensor

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0.2657, 0.2044, 0.1141],
         [0.6763, 0.3385, 0.6136]]))

In [8]:
tensor = torch.rand(3, 4)
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [9]:
if torch.accelerator.is_available():
    print('meh')

In [12]:
tensor = torch.rand(4, 4)
tensor

tensor([[0.5589, 0.0675, 0.6218, 0.5022],
        [0.1646, 0.5774, 0.8649, 0.8420],
        [0.2593, 0.5961, 0.7648, 0.7114],
        [0.5001, 0.9107, 0.3601, 0.0771]])

In [13]:
tensor[0]

tensor([0.5589, 0.0675, 0.6218, 0.5022])

In [14]:
tensor[:, 0]

tensor([0.5589, 0.1646, 0.2593, 0.5001])

In [15]:
tensor[..., -1]

tensor([0.5022, 0.8420, 0.7114, 0.0771])

In [16]:
tensor[:, 1] = 0
tensor

tensor([[0.5589, 0.0000, 0.6218, 0.5022],
        [0.1646, 0.0000, 0.8649, 0.8420],
        [0.2593, 0.0000, 0.7648, 0.7114],
        [0.5001, 0.0000, 0.3601, 0.0771]])

In [17]:
tensor.shape

torch.Size([4, 4])

In [18]:
torch.cat([tensor, tensor], dim=1)

tensor([[0.5589, 0.0000, 0.6218, 0.5022, 0.5589, 0.0000, 0.6218, 0.5022],
        [0.1646, 0.0000, 0.8649, 0.8420, 0.1646, 0.0000, 0.8649, 0.8420],
        [0.2593, 0.0000, 0.7648, 0.7114, 0.2593, 0.0000, 0.7648, 0.7114],
        [0.5001, 0.0000, 0.3601, 0.0771, 0.5001, 0.0000, 0.3601, 0.0771]])

In [19]:
y1 = tensor @ tensor.T
y1

tensor([[0.9511, 1.0527, 0.9778, 0.5421],
        [1.0527, 1.4841, 1.3032, 0.4587],
        [0.9778, 1.3032, 1.1583, 0.4600],
        [0.5421, 0.4587, 0.4600, 0.3858]])

In [20]:
y2 = tensor.matmul(tensor.T)

In [24]:
y3 = torch.rand_like(y1)
y3

tensor([[0.1306, 0.4385, 0.2632, 0.3683],
        [0.3319, 0.9416, 0.8815, 0.1536],
        [0.6691, 0.2974, 0.3693, 0.6866],
        [0.1519, 0.3139, 0.4688, 0.1364]])

In [25]:
torch.matmul(tensor, tensor.T, out=y3)

tensor([[0.9511, 1.0527, 0.9778, 0.5421],
        [1.0527, 1.4841, 1.3032, 0.4587],
        [0.9778, 1.3032, 1.1583, 0.4600],
        [0.5421, 0.4587, 0.4600, 0.3858]])

In [26]:
y3

tensor([[0.9511, 1.0527, 0.9778, 0.5421],
        [1.0527, 1.4841, 1.3032, 0.4587],
        [0.9778, 1.3032, 1.1583, 0.4600],
        [0.5421, 0.4587, 0.4600, 0.3858]])

In [27]:
tensor * tensor

tensor([[0.3123, 0.0000, 0.3866, 0.2522],
        [0.0271, 0.0000, 0.7481, 0.7089],
        [0.0673, 0.0000, 0.5849, 0.5061],
        [0.2501, 0.0000, 0.1297, 0.0059]])

In [28]:
tensor.mul(tensor)

tensor([[0.3123, 0.0000, 0.3866, 0.2522],
        [0.0271, 0.0000, 0.7481, 0.7089],
        [0.0673, 0.0000, 0.5849, 0.5061],
        [0.2501, 0.0000, 0.1297, 0.0059]])