In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.tensor(np_array)

In [4]:
x_ones = torch.ones_like(x_np)
x_ones

tensor([[1, 1],
        [1, 1]])

In [5]:
x_rand = torch.rand_like(x, dtype=torch.float)

In [6]:
x_rand

tensor([[0.2761, 0.0054],
        [0.7036, 0.5965]])

In [7]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
ones_tensor, zeros_tensor, rand_tensor

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0.7459, 0.4179, 0.7836],
         [0.7607, 0.2640, 0.9040]]))