In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.tensor(np_array)

In [4]:
x_ones = torch.ones_like(x_np)
x_ones

tensor([[1, 1],
        [1, 1]])

In [5]:
x_rand = torch.rand_like(x, dtype=torch.float)

In [6]:
x_rand

tensor([[0.3054, 0.2345],
        [0.7139, 0.6117]])

In [7]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
ones_tensor, zeros_tensor, rand_tensor

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0.5033, 0.4228, 0.6852],
         [0.6852, 0.8671, 0.8413]]))

In [8]:
tensor = torch.rand(3, 4)
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [9]:
if torch.accelerator.is_available():
    print('meh')

In [10]:
tensor = torch.rand(4, 4)
tensor

tensor([[0.5889, 0.4610, 0.4393, 0.4638],
        [0.3295, 0.0699, 0.6495, 0.2567],
        [0.0439, 0.5765, 0.3470, 0.1344],
        [0.9588, 0.4673, 0.4846, 0.2864]])

In [11]:
tensor[0]

tensor([0.5889, 0.4610, 0.4393, 0.4638])

In [12]:
tensor[:, 0]

tensor([0.5889, 0.3295, 0.0439, 0.9588])

In [13]:
tensor[..., -1]

tensor([0.4638, 0.2567, 0.1344, 0.2864])

In [14]:
tensor[:, 1] = 0
tensor

tensor([[0.5889, 0.0000, 0.4393, 0.4638],
        [0.3295, 0.0000, 0.6495, 0.2567],
        [0.0439, 0.0000, 0.3470, 0.1344],
        [0.9588, 0.0000, 0.4846, 0.2864]])

In [15]:
tensor.shape

torch.Size([4, 4])

In [16]:
torch.cat([tensor, tensor], dim=1)

tensor([[0.5889, 0.0000, 0.4393, 0.4638, 0.5889, 0.0000, 0.4393, 0.4638],
        [0.3295, 0.0000, 0.6495, 0.2567, 0.3295, 0.0000, 0.6495, 0.2567],
        [0.0439, 0.0000, 0.3470, 0.1344, 0.0439, 0.0000, 0.3470, 0.1344],
        [0.9588, 0.0000, 0.4846, 0.2864, 0.9588, 0.0000, 0.4846, 0.2864]])

In [17]:
y1 = tensor @ tensor.T
y1

tensor([[0.7549, 0.5984, 0.2406, 0.9104],
        [0.5984, 0.5963, 0.2743, 0.7042],
        [0.2406, 0.2743, 0.1404, 0.2487],
        [0.9104, 0.7042, 0.2487, 1.2362]])

In [18]:
y2 = tensor.matmul(tensor.T)

In [19]:
y3 = torch.rand_like(y1)
y3

tensor([[0.2823, 0.9034, 0.6712, 0.8991],
        [0.1380, 0.5657, 0.0823, 0.9352],
        [0.2326, 0.6647, 0.3536, 0.6451],
        [0.7000, 0.8410, 0.7795, 0.6917]])

In [20]:
torch.matmul(tensor, tensor.T, out=y3)

tensor([[0.7549, 0.5984, 0.2406, 0.9104],
        [0.5984, 0.5963, 0.2743, 0.7042],
        [0.2406, 0.2743, 0.1404, 0.2487],
        [0.9104, 0.7042, 0.2487, 1.2362]])

In [21]:
y3

tensor([[0.7549, 0.5984, 0.2406, 0.9104],
        [0.5984, 0.5963, 0.2743, 0.7042],
        [0.2406, 0.2743, 0.1404, 0.2487],
        [0.9104, 0.7042, 0.2487, 1.2362]])

In [22]:
tensor * tensor

tensor([[0.3468, 0.0000, 0.1930, 0.2151],
        [0.1086, 0.0000, 0.4218, 0.0659],
        [0.0019, 0.0000, 0.1204, 0.0181],
        [0.9194, 0.0000, 0.2348, 0.0820]])

In [23]:
tensor.mul(tensor)

tensor([[0.3468, 0.0000, 0.1930, 0.2151],
        [0.1086, 0.0000, 0.4218, 0.0659],
        [0.0019, 0.0000, 0.1204, 0.0181],
        [0.9194, 0.0000, 0.2348, 0.0820]])

In [24]:
agg = tensor.sum()

In [25]:
agg

tensor(4.9828)

In [26]:
type(agg)

torch.Tensor

In [27]:
agg.item()

4.982810020446777

In [28]:
type(agg.item())

float

In [29]:
tensor

tensor([[0.5889, 0.0000, 0.4393, 0.4638],
        [0.3295, 0.0000, 0.6495, 0.2567],
        [0.0439, 0.0000, 0.3470, 0.1344],
        [0.9588, 0.0000, 0.4846, 0.2864]])

In [30]:
tensor.add_(5)

tensor([[5.5889, 5.0000, 5.4393, 5.4638],
        [5.3295, 5.0000, 5.6495, 5.2567],
        [5.0438, 5.0000, 5.3470, 5.1344],
        [5.9588, 5.0000, 5.4846, 5.2864]])

In [31]:
t = torch.ones(5)

In [32]:
t

tensor([1., 1., 1., 1., 1.])

In [33]:
# Bridge with NumPy
n = t.numpy()

In [34]:
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [35]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [36]:
n

array([2., 2., 2., 2., 2.], dtype=float32)

In [37]:
t

tensor([2., 2., 2., 2., 2.])

In [38]:
n = np.ones(5)
t = torch.from_numpy(n)

In [39]:
np.add(n, 1, out=n)

array([2., 2., 2., 2., 2.])

In [40]:
n

array([2., 2., 2., 2., 2.])

In [41]:
t

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)