In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name

'int64'

In [5]:
a.itemsize # bytes per element

8

In [6]:
a.size

15

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.array([6, 7, 8])

In [9]:
b

array([6, 7, 8])

In [10]:
import numpy as np
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [11]:
a.dtype

dtype('int64')

In [12]:
b = np.array([1.5, 2, 5, 5.1])

In [13]:
b.dtype

dtype('float64')

In [14]:
a = np.array(1, 2, 3, 4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [15]:
a = np.array((1, 2, 3, 4))

In [16]:
a

array([1, 2, 3, 4])

In [17]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
b.dtype

dtype('float64')

In [19]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [20]:
c = np.array([[1 + 1j, 2], [3, 4]], dtype=complex)
c

array([[1.+1.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [24]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [22]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.empty((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [27]:
np.arange(0, 2, .3) # accepts int

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [31]:
range(0, 2, .3) # doesn't accept ints

TypeError: 'float' object cannot be interpreted as an integer

In [16]:
from numpy import pi
np.linspace(0, 2, 9) # هاتلي 9 نقط ما بين 0 و 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [34]:
x = np.linspace(0, 2 * pi, 9)

In [35]:
x

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
       3.92699082, 4.71238898, 5.49778714, 6.28318531])

In [36]:
f = np.sin(x)

In [37]:
f

array([ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,  7.07106781e-01,
        1.22464680e-16, -7.07106781e-01, -1.00000000e+00, -7.07106781e-01,
       -2.44929360e-16])

In [39]:
np.zeros((2, 2, 2, 2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [40]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [41]:
b = np.arange(12).reshape(4, 3)

In [43]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [44]:
c = np.arange(24).reshape(2, 3, 4)

In [45]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [46]:
print(np.arange(10_000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [50]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

c = a - b
c

array([20, 29, 38, 47])

In [51]:
b**2

array([0, 1, 4, 9])

In [52]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [55]:
np.sin(a) > 0

array([ True, False,  True, False])

In [56]:
a < 35

array([ True,  True, False, False])

In [58]:
a = np.array([[1, 1], [0, 1]])
b = np.array([[2, 0], [3, 4]])
a*b, a@b, a.dot(b)

(array([[2, 0],
        [0, 4]]),
 array([[5, 4],
        [3, 4]]),
 array([[5, 4],
        [3, 4]]))

In [ ]:
# https://numpy.org/doc/stable/user/quickstart.html#basic-operations

In [2]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [3]:
b

array([0, 1, 2, 3])

In [5]:
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

In [7]:
b += a

In [8]:
b

array([[1.51182162, 1.9504637 , 1.14415961],
       [1.94864945, 1.31183145, 1.42332645]])

In [9]:
a = a + b # لثد ضيقت واسعا

In [10]:
a += b

In [11]:
a

array([[4.02364325, 4.90092739, 3.28831923],
       [4.89729889, 3.6236629 , 3.8466529 ]])

In [12]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [13]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [14]:
a += b # لقد ضيقت واسعا

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [17]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)

In [18]:
c = a + b

In [19]:
c

array([1.        , 2.57079633, 4.14159265])

In [20]:
c.dtype.name

'float64'

In [21]:
d = np.exp(c * 1j)

In [22]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [23]:
"""
When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).
"""

'\nWhen operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).\n'

In [24]:
d.dtype.name

'complex128'

In [25]:
a = rg.random((2, 3))

In [26]:
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [27]:
a.sum()

np.float64(3.1057109529998157)

In [28]:
a.min()

np.float64(0.027559113243068367)

In [29]:
a.max()

np.float64(0.8277025938204418)

In [31]:
b = np.arange(12).reshape(3, 4)

In [32]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [35]:
b.sum(axis=1)

array([ 6, 22, 38])

In [36]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [37]:
b = np.arange(3)

In [38]:
b

array([0, 1, 2])

In [39]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [40]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [41]:
np.add(b, c)

array([1.        , 3.57079633, 6.14159265])

In [42]:
a = np.arange(10)**3

In [45]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [46]:
a[2]

np.int64(8)

In [47]:
a[2:5]

array([ 8, 27, 64])

In [48]:
a[2]

np.int64(8)

In [49]:
a[:6:2]

array([ 0,  8, 64])

In [50]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [51]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [52]:
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [3]:
def f(x, y):
    return 10 * x + y

In [4]:
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [55]:
b[2, 3]

np.int64(23)

In [56]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [2]:
# https://numpy.org/doc/stable/user/quickstart.html#indexing-slicing-and-iterating

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[0]

np.int64(0)

In [5]:
a[0: 3]

array([0, 1, 2])

In [6]:
a[:6:2] = 1000
a

array([1000,    1, 1000,    3, 1000,    5,    6,    7,    8,    9])

In [7]:
a[2:5]

array([1000,    3, 1000])

In [8]:
a[::-1]

array([   9,    8,    7,    6,    5, 1000,    3, 1000,    1, 1000])

In [9]:
a

array([1000,    1, 1000,    3, 1000,    5,    6,    7,    8,    9])

In [10]:
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
1.4422495703074083
9.999999999999998
1.7099759466766968
1.8171205928321397
1.912931182772389
2.0
2.080083823051904


In [10]:
def f(x, y):
    return x + y

b = np.fromfunction(f, (5, 4), dtype=int)

In [6]:
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [7]:
b[2, 3]

np.int64(5)

In [8]:
b[0: 5, 1]

array([1, 2, 3, 4, 5])

In [9]:
b[:, 1]

array([1, 2, 3, 4, 5])

In [10]:
b[1:3, :]

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [12]:
b[1:3]

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [13]:
b[-1]

array([4, 5, 6, 7])

In [2]:
c = np.array([[[  0,  1,  2],
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

In [3]:
c.shape

(2, 2, 3)

In [4]:
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [6]:
c[..., 2].shape

(2, 2)

In [7]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [8]:
c[:, :, 2]

array([[  2,  13],
       [102, 113]])

In [11]:
for row in b:
    print(row)

[0 1 2 3]
[1 2 3 4]
[2 3 4 5]
[3 4 5 6]
[4 5 6 7]


In [12]:
for element in b.flat:
    print(element)

0
1
2
3
1
2
3
4
2
3
4
5
3
4
5
6
4
5
6
7


# Shape manipulation

In [16]:
a = np.floor(10 * rg.random(3))

In [17]:
a

array([8., 4., 5.])

In [18]:
rg.random(3)

array([0.02755911, 0.75351311, 0.53814331])

In [19]:
a.shape

(3,)

In [20]:
a = np.floor(10 * rg.random((3, 4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [21]:
a.shape

(3, 4)

In [22]:
a.ravel()

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [23]:
a.reshape(6, 2)

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [24]:
a.T

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [26]:
a.T.shape

(4, 3)

In [27]:
a.shape

(3, 4)

In [28]:
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [29]:
a.reshape((2, 6))

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

In [30]:
# Auto dim detection
a.reshape(6, -1)

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

# Stacking together different arrays

In [6]:
a = np.floor(10 * rg.random((2, 2)))
b = np.floor(10 * rg.random((2, 2)))
a, b

(array([[8., 4.],
        [5., 0.]]),
 array([[7., 5.],
        [3., 7.]]))

In [7]:
np.vstack((a, b))

array([[8., 4.],
       [5., 0.],
       [7., 5.],
       [3., 7.]])

In [8]:
np.hstack((a, b))

array([[8., 4., 7., 5.],
       [5., 0., 3., 7.]])

In [9]:
a

array([[8., 4.],
       [5., 0.]])

In [10]:
from numpy import newaxis

np.column_stack((a, b))

array([[8., 4., 7., 5.],
       [5., 0., 3., 7.]])

In [11]:
a = np.array([4, 2])
b = np.array([3, 8])

In [12]:
np.hstack((a, b))

array([4, 2, 3, 8])

In [13]:
a[:, newaxis]

array([[4],
       [2]])

In [14]:
a[:, newaxis].shape

(2, 1)

In [15]:
a.shape

(2,)

In [17]:
a, b

(array([4, 2]), array([3, 8]))

In [16]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[4, 3],
       [2, 8]])

In [18]:
np.hstack((a[:, newaxis], b[:, newaxis])).shape

(2, 2)

In [19]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4, 3],
       [2, 8]])

In [20]:
np.vstack((a[:, newaxis], b[:, newaxis]))

array([[4],
       [2],
       [3],
       [8]])

In [ ]:
np.r_[1:4, 0, 4]

In [ ]:
np.c_[1:4, 0, 4]

# Splitting one array into several smaller ones

In [21]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[3., 4., 1., 4., 2., 2., 7., 2., 4., 9., 9., 7.],
       [5., 2., 1., 9., 5., 1., 6., 7., 6., 9., 0., 5.]])

In [22]:
np.hsplit(a, 3) # to three pieces

[array([[3., 4., 1., 4.],
        [5., 2., 1., 9.]]),
 array([[2., 2., 7., 2.],
        [5., 1., 6., 7.]]),
 array([[4., 9., 9., 7.],
        [6., 9., 0., 5.]])]

In [24]:
np.hsplit(a, (3, 4)) # after third and fourth columns

[array([[3., 4., 1.],
        [5., 2., 1.]]),
 array([[4.],
        [9.]]),
 array([[2., 2., 7., 2., 4., 9., 9., 7.],
        [5., 1., 6., 7., 6., 9., 0., 5.]])]

In [25]:
np.hsplit(a, (3, 4, 5))

[array([[3., 4., 1.],
        [5., 2., 1.]]),
 array([[4.],
        [9.]]),
 array([[2.],
        [5.]]),
 array([[2., 7., 2., 4., 9., 9., 7.],
        [1., 6., 7., 6., 9., 0., 5.]])]

In [28]:
np.hsplit(a, (3, )) # after third

[array([[3., 4., 1.],
        [5., 2., 1.]]),
 array([[4., 2., 2., 7., 2., 4., 9., 9., 7.],
        [9., 5., 1., 6., 7., 6., 9., 0., 5.]])]

# copies and views

In [29]:
a = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
])

In [30]:
b = a

In [31]:
b is a

True

In [35]:
def f(x):
    print(id(x))

In [36]:
id(a)

123368947357840

In [37]:
f(a)

123368947357840


In [38]:
# view or shallow copy

In [39]:
c = a.view()

In [40]:
c is a

False

In [41]:
c.base is a

True

In [45]:
a = a.reshape((2, 6))

In [46]:
c.shape

(3, 4)

In [47]:
a.shape

(2, 6)

In [48]:
# result => reshaping doesn't affect the view

In [49]:
a = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
])

In [50]:
c = a.view()

In [52]:
a[0, 3] = 10001

In [53]:
a

array([[    0,     1,     2, 10001],
       [    4,     5,     6,     7],
       [    8,     9,    10,    11]])

In [54]:
c

array([[    0,     1,     2, 10001],
       [    4,     5,     6,     7],
       [    8,     9,    10,    11]])

In [55]:
# slicing returns view (independent shapes but dependent values)

In [56]:
s = a[:, 1:3]

In [57]:
s[:] = 10

In [58]:
a

array([[    0,    10,    10, 10001],
       [    4,    10,    10,     7],
       [    8,    10,    10,    11]])

In [60]:
d = a.copy() # complete copy

In [61]:
d is a

False

In [62]:
d.base is a

False

In [63]:
d

array([[    0,    10,    10, 10001],
       [    4,    10,    10,     7],
       [    8,    10,    10,    11]])

In [64]:
d[0, 0] = 63

In [65]:
d

array([[   63,    10,    10, 10001],
       [    4,    10,    10,     7],
       [    8,    10,    10,    11]])

In [67]:
a # totally independent (deep copy)

array([[    0,    10,    10, 10001],
       [    4,    10,    10,     7],
       [    8,    10,    10,    11]])

In [68]:
y = a[:]

In [69]:
y is a

False

In [71]:
y.base is a # view

True

In [72]:
y.shape

(3, 4)

In [73]:
y = y.reshape((6, 2))
y

array([[    0,    10],
       [   10, 10001],
       [    4,    10],
       [   10,     7],
       [    8,    10],
       [   10,    11]])

In [74]:
y[0, 0] = 63

In [75]:
y

array([[   63,    10],
       [   10, 10001],
       [    4,    10],
       [   10,     7],
       [    8,    10],
       [   10,    11]])

In [76]:
a

array([[   63,    10,    10, 10001],
       [    4,    10,    10,     7],
       [    8,    10,    10,    11]])

In [77]:
# sometimes you'll need to call .copy after slicing, for example when you only need part of a huge array of intermediate result

In [78]:
a = np.arange(int(1e8))

In [79]:
a

array([       0,        1,        2, ..., 99999997, 99999998, 99999999],
      shape=(100000000,))

In [80]:
b = a[:100].copy()

In [81]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [82]:
del a

In [83]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [84]:
a = np.arange(int(1e8))

In [85]:
b = a[:100]

In [86]:
del a

In [88]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Advanced indexing and index tricks

In [5]:
a = np.arange(12) ** 2
i = np.array([1, 1, 3, 8, 5])
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [3]:
a[i]

array([ 1,  1,  9, 64, 25])

In [4]:
j = np.array([[3, 4], [9, 7]])
a[j]

array([[ 9, 16],
       [81, 49]])

In [6]:
palette = np.array([[0, 0, 0],         # black
                    [255, 0, 0],       # red
                    [0, 255, 0],       # green
                    [0, 0, 255],       # blue
                    [255, 255, 255]])

In [7]:
image = np.array([[0, 1, 2, 0],
                  [0, 3, 4, 0]])

In [8]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [9]:
a = np.arange(12).reshape(3, 4)

In [10]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
i = np.array([[0, 1], [1, 2]])
j = np.array([[2, 1], [3, 3]])

In [12]:
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [13]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [14]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [15]:
l = (i, j)
a[l]

array([[ 2,  5],
       [ 7, 11]])