In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype.name

'int64'

In [5]:
a.itemsize # bytes per element

8

In [6]:
a.size

15

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.array([6, 7, 8])

In [9]:
b

array([6, 7, 8])

In [10]:
import numpy as np
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [11]:
a.dtype

dtype('int64')

In [12]:
b = np.array([1.5, 2, 5, 5.1])

In [13]:
b.dtype

dtype('float64')

In [14]:
a = np.array(1, 2, 3, 4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [15]:
a = np.array((1, 2, 3, 4))

In [16]:
a

array([1, 2, 3, 4])

In [17]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
b.dtype

dtype('float64')

In [19]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [20]:
c = np.array([[1 + 1j, 2], [3, 4]], dtype=complex)
c

array([[1.+1.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [24]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [22]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.empty((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [27]:
np.arange(0, 2, .3) # accepts int

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [31]:
range(0, 2, .3) # doesn't accept ints

TypeError: 'float' object cannot be interpreted as an integer

In [33]:
from numpy import pi
np.linspace(0, 2, 9) # هاتلي 9 نقط ما بين 0 و 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [34]:
x = np.linspace(0, 2 * pi, 9)

In [35]:
x

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
       3.92699082, 4.71238898, 5.49778714, 6.28318531])

In [36]:
f = np.sin(x)

In [37]:
f

array([ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,  7.07106781e-01,
        1.22464680e-16, -7.07106781e-01, -1.00000000e+00, -7.07106781e-01,
       -2.44929360e-16])

In [39]:
np.zeros((2, 2, 2, 2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [40]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [41]:
b = np.arange(12).reshape(4, 3)

In [43]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [44]:
c = np.arange(24).reshape(2, 3, 4)

In [45]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [46]:
print(np.arange(10_000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [50]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

c = a - b
c

array([20, 29, 38, 47])

In [51]:
b**2

array([0, 1, 4, 9])

In [52]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [55]:
np.sin(a) > 0

array([ True, False,  True, False])

In [56]:
a < 35

array([ True,  True, False, False])

In [58]:
a = np.array([[1, 1], [0, 1]])
b = np.array([[2, 0], [3, 4]])
a*b, a@b, a.dot(b)

(array([[2, 0],
        [0, 4]]),
 array([[5, 4],
        [3, 4]]),
 array([[5, 4],
        [3, 4]]))

In [ ]:
# https://numpy.org/doc/stable/user/quickstart.html#basic-operations