In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
a.shape

(2, 3)

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a[0]

np.int64(1)

In [7]:
a[0] = 10

In [8]:
a

array([10,  2,  3,  4,  5,  6])

In [9]:
a[:3]

array([10,  2,  3])

In [10]:
l = [1, 2]
l2 = l[:]
l2[0] = 2
l, l2

([1, 2], [2, 2])

In [11]:
b = a[3:]

In [12]:
b

array([4, 5, 6])

In [13]:
b[0] = 40

In [14]:
a

array([10,  2,  3, 40,  5,  6])

In [15]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [16]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
a[1, 3]

np.int64(8)

In [18]:
a.ndim

2

In [19]:
a.shape

(3, 4)

In [20]:
len(a.shape) == a.ndim

True

In [21]:
a.size

12

In [22]:
import math
math.prod(a.shape)

12

In [23]:
type(a.shape)

tuple

In [25]:
type(a.shape[0])

int

In [26]:
a.dtype

dtype('int64')

In [27]:
np.zeros(2)

array([0., 0.])

In [28]:
np.ones(2)

array([1., 1.])

In [29]:
np.empty(2)

array([1., 1.])

In [30]:
np.arange(4)

array([0, 1, 2, 3])

In [31]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [32]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
np.ones(2, dtype=np.int64)

array([1, 1])

In [34]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [35]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [36]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [38]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
x = np.array([[1, 2], [3, 4]])

In [42]:
x

array([[1, 2],
       [3, 4]])

In [40]:
y = np.array([[5, 6]])

In [43]:
y

array([[5, 6]])

In [46]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])