In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
a.shape

(2, 3)

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [7]:
a[0]

np.int64(1)

In [8]:
a[0] = 10

In [10]:
a

array([10,  2,  3,  4,  5,  6])

In [11]:
a[:3]

array([10,  2,  3])

In [12]:
l = [1, 2]
l2 = l[:]
l2[0] = 2
l, l2

([1, 2], [2, 2])

In [13]:
b = a[3:]

In [14]:
b

array([4, 5, 6])

In [15]:
b[0] = 40

In [16]:
a

array([10,  2,  3, 40,  5,  6])

In [17]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [18]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])