In [1]:
import tensorflow as tf

2025-11-27 18:04:14.060820: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [15]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])
x, x.shape, x.dtype

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.]], dtype=float32)>,
 TensorShape([2, 3]),
 tf.float32)

In [3]:
x + x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [4]:
5 * x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5., 10., 15.],
       [20., 25., 30.]], dtype=float32)>

In [5]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [6]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [9]:
tf.concat([x, x, x], axis=0)

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [10]:
tf.nn.softmax(x, axis=-1) # -1 means last dimension (least dimension)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [12]:
tf.nn.softmax(x, axis=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [13]:
tf.nn.softmax(x, axis=0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.04742587, 0.04742587, 0.04742587],
       [0.95257413, 0.95257413, 0.95257413]], dtype=float32)>

In [16]:
y = tf.constant([[[1., 2., 3.],
                 [4., 5., 6.]],
                 [[1., 2., 3.],
                 [4., 5., 6.]]])
y

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]]], dtype=float32)>

In [19]:
tf.nn.softmax(y, axis=0)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5]],

       [[0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5]]], dtype=float32)>

In [20]:
tf.nn.softmax(y, axis=1)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0.04742588, 0.04742588, 0.04742588],
        [0.95257413, 0.95257413, 0.95257413]],

       [[0.04742588, 0.04742587, 0.04742587],
        [0.95257413, 0.95257413, 0.95257413]]], dtype=float32)>

In [22]:
tf.nn.softmax(y, axis=2), tf.nn.softmax(y, axis=-1)

(<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
 array([[[0.09003057, 0.24472848, 0.66524094],
         [0.09003057, 0.24472848, 0.66524094]],
 
        [[0.09003057, 0.24472848, 0.66524094],
         [0.09003057, 0.24472848, 0.66524094]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
 array([[[0.09003057, 0.24472848, 0.66524094],
         [0.09003057, 0.24472848, 0.66524094]],
 
        [[0.09003057, 0.24472848, 0.66524094],
         [0.09003057, 0.24472848, 0.66524094]]], dtype=float32)>)

In [23]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

In [24]:
tf.convert_to_tensor([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [25]:
# بص للتكيف والسهولة
tf.reduce_sum([1, 2, 3])

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [26]:
if tf.config.list_physical_devices('GPU'):
    print("TensorFlow **IS** using the GPU")
else:
    print("TensorFlow **IS** using the CPU")

TensorFlow **IS** using the CPU


In [27]:
# tf.Tensor objects are immutable
# if you wanna mutable => tf.Variable

In [28]:
"""
https://www.tensorflow.org/guide/basics#variables
"""

'\nhttps://www.tensorflow.org/guide/basics#variables\n'

In [2]:
var = tf.Variable([0, 0, 0.])

2025-11-27 18:04:43.958701: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (100)


In [3]:
var

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [4]:
var.assign([1, 2, 3])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [5]:
var.assign_add([1, 1, 1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [6]:
# https://www.tensorflow.org/guide/basics#automatic_differentiation

Automatic differentiation

In [9]:
x = tf.Variable(1.0)

def f(x):
    y = x**2 + x*2 - 5
    return y

In [10]:
f(x)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [11]:
with tf.GradientTape() as tape:
    y = f(x)

g_x = tape.gradient(y, x)
g_x

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [ ]:
"""
https://www.tensorflow.org/guide/basics#graphs_and_tffunction
"""