In [1]:
import tensorflow as tf

2025-11-25 20:19:50.445948: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [15]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])
x, x.shape, x.dtype

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.]], dtype=float32)>,
 TensorShape([2, 3]),
 tf.float32)

In [3]:
x + x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [4]:
5 * x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5., 10., 15.],
       [20., 25., 30.]], dtype=float32)>

In [5]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [6]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [9]:
tf.concat([x, x, x], axis=0)

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [10]:
tf.nn.softmax(x, axis=-1) # -1 means last dimension (least dimension)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [12]:
tf.nn.softmax(x, axis=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [13]:
tf.nn.softmax(x, axis=0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.04742587, 0.04742587, 0.04742587],
       [0.95257413, 0.95257413, 0.95257413]], dtype=float32)>

In [16]:
y = tf.constant([[[1., 2., 3.],
                 [4., 5., 6.]],
                 [[1., 2., 3.],
                 [4., 5., 6.]]])
y

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]]], dtype=float32)>

In [19]:
tf.nn.softmax(y, axis=0)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5]],

       [[0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5]]], dtype=float32)>

In [20]:
tf.nn.softmax(y, axis=1)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0.04742588, 0.04742588, 0.04742588],
        [0.95257413, 0.95257413, 0.95257413]],

       [[0.04742588, 0.04742587, 0.04742587],
        [0.95257413, 0.95257413, 0.95257413]]], dtype=float32)>

In [22]:
tf.nn.softmax(y, axis=2), tf.nn.softmax(y, axis=-1)

(<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
 array([[[0.09003057, 0.24472848, 0.66524094],
         [0.09003057, 0.24472848, 0.66524094]],
 
        [[0.09003057, 0.24472848, 0.66524094],
         [0.09003057, 0.24472848, 0.66524094]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
 array([[[0.09003057, 0.24472848, 0.66524094],
         [0.09003057, 0.24472848, 0.66524094]],
 
        [[0.09003057, 0.24472848, 0.66524094],
         [0.09003057, 0.24472848, 0.66524094]]], dtype=float32)>)

In [23]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

In [24]:
tf.convert_to_tensor([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [25]:
# بص للتكيف والسهولة
tf.reduce_sum([1, 2, 3])

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [26]:
if tf.config.list_physical_devices('GPU'):
    print("TensorFlow **IS** using the GPU")
else:
    print("TensorFlow **IS** using the CPU")

TensorFlow **IS** using the CPU


In [ ]:
# tf.Tensor objects are immutable
# if you wanna mutable => tf.Variable