In [1]:
import tensorflow as tf
import numpy as np

2025-12-08 12:59:38.819843: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
#  single value, and no "axes"."scalar" or "rank-0"
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


2025-12-08 12:59:46.399949: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [3]:
rank_1_tensor = tf.constant([2, 3, 4])
print(rank_1_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [52]:
rank_2_tensor = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
], dtype=tf.int64)
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int64)


In [5]:
rank3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29]],
])

In [6]:
rank3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

In [7]:
np.array(rank_2_tensor)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
rank_2_tensor.numpy()

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

print(tf.add(a, b))
print(tf.multiply(a, b))
print(tf.matmul(a, b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [10]:
print(a + b)
print(a * b)
print(a @ b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [11]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

In [12]:
tf.reduce_max(c)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [13]:
tf.math.argmax(c)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0])>

In [15]:
tf.nn.softmax(c, axis = -1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>

In [16]:
tf.nn.softmax(c, axis = 1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>

In [17]:
tf.nn.softmax(c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>

In [19]:
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.,  5.],
       [10.,  1.]], dtype=float32)>

In [18]:
tf.nn.softmax(c, axis = 0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.00247262, 0.98201376],
       [0.9975274 , 0.01798621]], dtype=float32)>

In [20]:
tf.convert_to_tensor([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [21]:
tf.reduce_max([1, 2, 3])

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [22]:
tf.reduce_max(np.array([1, 2, 3]))

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [23]:
c._rank()

2

In [24]:
c.shape

TensorShape([2, 2])

In [25]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

In [26]:
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
rank_4_tensor.dtype

tf.float32

In [28]:
rank_4_tensor.ndim

4

In [29]:
rank_4_tensor.shape

TensorShape([3, 2, 4, 5])

In [30]:
rank_4_tensor.shape[0]

3

In [31]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [32]:
tf.size(rank_4_tensor).numpy()

np.int32(120)

In [33]:
tf.rank(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [42]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])

In [43]:
rank_1_tensor.numpy()

array([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34], dtype=int32)

In [44]:
rank_1_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [45]:
rank_1_tensor[0].numpy()

np.int32(0)

In [46]:
rank_1_tensor[:].numpy()

array([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34], dtype=int32)

In [47]:
rank_1_tensor[:4].numpy()

array([0, 1, 1, 2], dtype=int32)

In [48]:
rank_1_tensor[4:].numpy()

array([ 3,  5,  8, 13, 21, 34], dtype=int32)

In [49]:
rank_1_tensor[2:7].numpy()

array([1, 2, 3, 5, 8], dtype=int32)

In [50]:
rank_1_tensor[::2].numpy()

array([ 0,  1,  3,  8, 21], dtype=int32)

In [51]:
rank_1_tensor[::-1].numpy()

array([34, 21, 13,  8,  5,  3,  2,  1,  1,  0], dtype=int32)

In [53]:
rank_2_tensor.numpy()

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
rank_2_tensor[1, 1].numpy()

np.int64(4)

In [55]:
rank_2_tensor[1, :]

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([3, 4])>

In [56]:
rank_2_tensor[:, 1]

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 4, 6])>

In [58]:
rank_2_tensor[-1, :].numpy()

array([5, 6])

In [59]:
rank_2_tensor[0, -1]

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [61]:
rank_2_tensor[1:, :].numpy()

array([[3, 4],
       [5, 6]])

In [62]:
rank3_tensor[:, :, 4]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  9],
       [14, 19],
       [24, 29]], dtype=int32)>

manipulating shapes

In [63]:
x = tf.constant([[1], [2], [3]])

In [64]:
x.shape

TensorShape([3, 1])

In [65]:
x.shape.as_list()

[3, 1]

In [67]:
x_ = tf.reshape(x, [1, 3])

In [68]:
x.shape, x_.shape

(TensorShape([3, 1]), TensorShape([1, 3]))

In [69]:
rank3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

In [70]:
tf.reshape(rank3_tensor, [-1])

<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int32)>