In [1]:
import tensorflow as tf
import numpy as np

2025-12-15 21:32:27.083843: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
#  single value, and no "axes"."scalar" or "rank-0"
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


2025-12-13 01:58:40.040249: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [3]:
rank_1_tensor = tf.constant([2, 3, 4])
print(rank_1_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [4]:
rank_2_tensor = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
], dtype=tf.int64)
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int64)


In [5]:
rank3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29]],
])

In [6]:
rank3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

In [7]:
np.array(rank_2_tensor)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
rank_2_tensor.numpy()

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

print(tf.add(a, b))
print(tf.multiply(a, b))
print(tf.matmul(a, b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [10]:
print(a + b)
print(a * b)
print(a @ b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [11]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

In [12]:
tf.reduce_max(c)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [13]:
tf.math.argmax(c)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0])>

In [14]:
tf.nn.softmax(c, axis = -1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>

In [15]:
tf.nn.softmax(c, axis = 1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>

In [16]:
tf.nn.softmax(c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>

In [17]:
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.,  5.],
       [10.,  1.]], dtype=float32)>

In [18]:
tf.nn.softmax(c, axis = 0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.00247262, 0.98201376],
       [0.9975274 , 0.01798621]], dtype=float32)>

In [19]:
tf.convert_to_tensor([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [20]:
tf.reduce_max([1, 2, 3])

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [21]:
tf.reduce_max(np.array([1, 2, 3]))

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [22]:
c._rank()

2

In [23]:
c.shape

TensorShape([2, 2])

In [24]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

In [25]:
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor.dtype

tf.float32

In [27]:
rank_4_tensor.ndim

4

In [28]:
rank_4_tensor.shape

TensorShape([3, 2, 4, 5])

In [29]:
rank_4_tensor.shape[0]

3

In [30]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [31]:
tf.size(rank_4_tensor).numpy()

np.int32(120)

In [32]:
tf.rank(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [33]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])

In [34]:
rank_1_tensor.numpy()

array([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34], dtype=int32)

In [35]:
rank_1_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [36]:
rank_1_tensor[0].numpy()

np.int32(0)

In [37]:
rank_1_tensor[:].numpy()

array([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34], dtype=int32)

In [38]:
rank_1_tensor[:4].numpy()

array([0, 1, 1, 2], dtype=int32)

In [39]:
rank_1_tensor[4:].numpy()

array([ 3,  5,  8, 13, 21, 34], dtype=int32)

In [40]:
rank_1_tensor[2:7].numpy()

array([1, 2, 3, 5, 8], dtype=int32)

In [41]:
rank_1_tensor[::2].numpy()

array([ 0,  1,  3,  8, 21], dtype=int32)

In [42]:
rank_1_tensor[::-1].numpy()

array([34, 21, 13,  8,  5,  3,  2,  1,  1,  0], dtype=int32)

In [43]:
rank_2_tensor.numpy()

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
rank_2_tensor[1, 1].numpy()

np.int64(4)

In [45]:
rank_2_tensor[1, :]

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([3, 4])>

In [46]:
rank_2_tensor[:, 1]

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 4, 6])>

In [47]:
rank_2_tensor[-1, :].numpy()

array([5, 6])

In [48]:
rank_2_tensor[0, -1]

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [49]:
rank_2_tensor[1:, :].numpy()

array([[3, 4],
       [5, 6]])

In [50]:
rank3_tensor[:, :, 4]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  9],
       [14, 19],
       [24, 29]], dtype=int32)>

manipulating shapes

In [51]:
x = tf.constant([[1], [2], [3]])

In [52]:
x.shape

TensorShape([3, 1])

In [53]:
x.shape.as_list()

[3, 1]

In [54]:
x_ = tf.reshape(x, [1, 3])

In [55]:
x.shape, x_.shape

(TensorShape([3, 1]), TensorShape([1, 3]))

In [56]:
rank3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

In [57]:
tf.reshape(rank3_tensor, [-1])

<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int32)>

In [58]:
data = []

In [59]:
print(tf.reshape(rank3_tensor, [3*2, 5]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [60]:
print(tf.reshape(rank3_tensor, [3, -1]))

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


In [63]:
rank3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

In [64]:
# Bad examples: don't do this
# it did what it should do, it reshaped but didn't reorder axis
print(tf.reshape(rank3_tensor, [2, 3, 5]))

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32)


In [65]:
print(tf.reshape(rank3_tensor, [5, 6]))

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32)


In [66]:
try:
    tf.reshape(rank3_tensor, [7, -1])
except Exception as e:
    print(f"{type(e).__name__}: {e}")

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]


2025-12-13 02:04:02.843051: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: INVALID_ARGUMENT: Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7


In [67]:
inputs = tf.keras.Input(shape=(28, 28, 1))
print(inputs.shape)

(None, 28, 28, 1)


In [68]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
the_f64_tensor

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.2, 3.3, 4.4])>

In [69]:
the_f16_tensor = tf.cast(the_f64_tensor, tf.float16)
the_f16_tensor

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([2.2, 3.3, 4.4], dtype=float16)>

In [70]:
the_u8_tensor = tf.cast(the_f16_tensor, tf.uint8)
the_u8_tensor

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([2, 3, 4], dtype=uint8)>

In [71]:
x = tf.constant([1, 2, 3])
y = tf.constant(2)
z = tf.constant([2, 2, 2])

In [72]:
print(tf.multiply(x, 2))

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [73]:
print(x * y)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [74]:
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [75]:
x = tf.reshape(x, [3, 1])
y = tf.range(1, 5)
x

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [76]:
y

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [79]:
x.shape, y.shape

(TensorShape([3, 1]), TensorShape([4]))

In [81]:
x, y

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[1],
        [2],
        [3]], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>)

In [82]:
x_stretch = tf.constant([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]])
y_stretch = tf.constant([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
x_stretch * y_stretch

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]], dtype=int32)>

Most of the time, broadcasting is both time and space efficient, as the broadcast operation never materializes the expanded tensors in memory.

In [84]:
tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3])
# this materializes the tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

ragged tensors

In [86]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]
]

In [88]:
try:
    tensor = tf.constant(ragged_list)
except Exception as e:
    print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


In [89]:
ragged_tensor = tf.ragged.constant(ragged_list)
ragged_tensor

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>

In [90]:
ragged_tensor.shape

TensorShape([4, None])

string tensors

In [91]:
scalar_string_tensor = tf.constant("Gray wolf")
scalar_string_tensor

<tf.Tensor: shape=(), dtype=string, numpy=b'Gray wolf'>

In [92]:
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
tensor_of_strings

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'Gray wolf', b'Quick brown fox', b'Lazy dog'], dtype=object)>

In [93]:
tf.constant("🥳👍")

<tf.Tensor: shape=(), dtype=string, numpy=b'\xf0\x9f\xa5\xb3\xf0\x9f\x91\x8d'>

In [94]:
tf.strings.split(scalar_string_tensor, sep=" ")

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Gray', b'wolf'], dtype=object)>

In [95]:
tf.strings.split(tensor_of_strings, sep=" ")

<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>

In [96]:
txt = tf.constant("1 10 100")

In [97]:
tf.strings.to_number(tf.strings.split(txt, sep=" "))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([  1.,  10., 100.], dtype=float32)>

In [2]:
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))

2025-12-15 21:37:02.239058: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [3]:
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)

In [4]:
byte_strings

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'D', b'u', b'c', b'k'], dtype=object)>

In [5]:
byte_ints

<tf.Tensor: shape=(4,), dtype=uint8, numpy=array([ 68, 117,  99, 107], dtype=uint8)>

In [6]:
unicode_bytes = tf.constant("アヒル 🦆")
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, "UTF-8")

In [7]:
unicode_bytes

<tf.Tensor: shape=(), dtype=string, numpy=b'\xe3\x82\xa2\xe3\x83\x92\xe3\x83\xab \xf0\x9f\xa6\x86'>

In [8]:
unicode_char_bytes

<tf.Tensor: shape=(5,), dtype=string, numpy=
array([b'\xe3\x82\xa2', b'\xe3\x83\x92', b'\xe3\x83\xab', b' ',
       b'\xf0\x9f\xa6\x86'], dtype=object)>

In [10]:
unicode_values = tf.strings.unicode_decode(unicode_bytes, "UTF-8")

In [12]:
unicode_values

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 12450,  12498,  12523,     32, 129414], dtype=int32)>

In [13]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])

In [17]:
print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [16]:
print(tf.sparse.to_dense(sparse_tensor))

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
