In [1]:
import tensorflow as tf

2025-12-15 21:49:39.193837: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
a = tf.constant([0, 1])

2025-12-15 21:49:49.874008: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [6]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [4]:
a[0] = 4

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [8]:
import tensorflow as tf

tf.debugging.set_log_device_placement(True)

In [9]:
my_tensor = tf.constant([[1, 2], [3, 4.]])
my_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [10]:
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])

In [11]:
my_variable = tf.Variable(my_tensor)

In [12]:
my_variable.shape

TensorShape([2, 2])

In [13]:
my_variable.dtype

tf.float32

In [14]:
my_variable.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [15]:
my_variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [17]:
print(tf.convert_to_tensor(my_variable))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [18]:
tf.math.argmax(my_variable)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [21]:
my_variable[tf.math.argmax(my_variable).numpy()[0], tf.math.argmax(my_variable).numpy()[1]]

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [22]:
# create a new variable, it doesn't affect the original
tf.reshape(my_variable, [1, 4])

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 2., 3., 4.]], dtype=float32)>

In [23]:
my_variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [24]:
a = tf.Variable([2., 3])
a.assign([1, 2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [25]:
a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [26]:
# uses the same memory, cannot assign things that doesn't fit into this memory used
a.assign([1., 2, 3])

ValueError: Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (2,), and the assigned value shape (3,) are incompatible.

In [27]:
a.assign([1, 2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [28]:
a.assign([b'1', b'2'])

TypeError: Cannot convert [b'1', b'2'] to EagerTensor of dtype float

In [29]:
# duplicating creates a new variable => no share of data
a = tf.Variable([2., 3])
b = tf.Variable(a)

In [30]:
a.assign([5, 6])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([5., 6.], dtype=float32)>

In [31]:
b

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [33]:
a.numpy()

array([5., 6.], dtype=float32)

In [34]:
b.numpy()

array([2., 3.], dtype=float32)

In [35]:
a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([5., 6.], dtype=float32)>

In [36]:
a.assign_add([2, 3])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([7., 9.], dtype=float32)>

In [37]:
a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([7., 9.], dtype=float32)>