In [5]:
import tensorflow as tf

In [6]:
a = tf.constant([0, 1])

In [7]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [8]:
a[0] = 4

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [9]:
import tensorflow as tf

tf.debugging.set_log_device_placement(True)

In [10]:
my_tensor = tf.constant([[1, 2], [3, 4.]])
my_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [11]:
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])

In [12]:
my_variable = tf.Variable(my_tensor)

In [13]:
my_variable.shape

TensorShape([2, 2])

In [14]:
my_variable.dtype

tf.float32

In [15]:
my_variable.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [16]:
my_variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [17]:
print(tf.convert_to_tensor(my_variable))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [18]:
tf.math.argmax(my_variable)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [19]:
my_variable[tf.math.argmax(my_variable).numpy()[0], tf.math.argmax(my_variable).numpy()[1]]

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [20]:
# create a new variable, it doesn't affect the original
tf.reshape(my_variable, [1, 4])

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 2., 3., 4.]], dtype=float32)>

In [21]:
my_variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [22]:
a = tf.Variable([2., 3])
a.assign([1, 2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [23]:
a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [24]:
# uses the same memory, cannot assign things that doesn't fit into this memory used
a.assign([1., 2, 3])

ValueError: Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (2,), and the assigned value shape (3,) are incompatible.

In [25]:
a.assign([1, 2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [26]:
a.assign([b'1', b'2'])

TypeError: Cannot convert [b'1', b'2'] to EagerTensor of dtype float

In [27]:
# duplicating creates a new variable => no share of data
a = tf.Variable([2., 3])
b = tf.Variable(a)

In [28]:
a.assign([5, 6])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([5., 6.], dtype=float32)>

In [29]:
b

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [30]:
a.numpy()

array([5., 6.], dtype=float32)

In [31]:
b.numpy()

array([2., 3.], dtype=float32)

In [32]:
a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([5., 6.], dtype=float32)>

In [33]:
a.assign_add([2, 3])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([7., 9.], dtype=float32)>

In [34]:
a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([7., 9.], dtype=float32)>

In [35]:
a.assign_sub(([7, 9]))

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [36]:
a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [37]:
a.numpy()

array([0., 0.], dtype=float32)

In [38]:
a = tf.Variable(my_tensor, name="Mark")
a

<tf.Variable 'Mark:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [39]:
b = tf.Variable(my_tensor + 1, name="Mark")
b

<tf.Variable 'Mark:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [40]:
a == b

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False, False],
       [False, False]])>

In [42]:
b = b - 1

In [43]:
step_counter = tf.Variable(1, trainable=False)

In [44]:
with tf.device('CPU:0'):
    a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
    b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
    c = tf.matmul(a, b)
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 28.],
       [49., 64.]], dtype=float32)>